import type { DecisionTreeChallenge } from "./decision-tree-types";

export const DECISION_TREE_CHALLENGES: DecisionTreeChallenge[] = [
  {
    id: "loan-approval-easy",
    title: "Loan Approval System",
    description: "Build a decision tree to approve or reject loan applications",
    emoji: "💰",
    targetDepth: 3,
    minAccuracy: 85,
    dataset: [
      {
        id: 1,
        features: { income: 50000, creditScore: 720, age: 30, employed: true },
        label: "approved",
        emoji: "✅",
      },
      {
        id: 2,
        features: { income: 30000, creditScore: 650, age: 25, employed: true },
        label: "approved",
        emoji: "✅",
      },
      {
        id: 3,
        features: { income: 80000, creditScore: 780, age: 45, employed: true },
        label: "approved",
        emoji: "✅",
      },
      {
        id: 4,
        features: { income: 25000, creditScore: 600, age: 22, employed: false },
        label: "rejected",
        emoji: "❌",
      },
      {
        id: 5,
        features: { income: 20000, creditScore: 550, age: 28, employed: true },
        label: "rejected",
        emoji: "❌",
      },
      {
        id: 6,
        features: { income: 60000, creditScore: 700, age: 35, employed: true },
        label: "approved",
        emoji: "✅",
      },
      {
        id: 7,
        features: { income: 15000, creditScore: 500, age: 20, employed: false },
        label: "rejected",
        emoji: "❌",
      },
      {
        id: 8,
        features: { income: 90000, creditScore: 800, age: 50, employed: true },
        label: "approved",
        emoji: "✅",
      },
      {
        id: 9,
        features: { income: 35000, creditScore: 620, age: 27, employed: true },
        label: "approved",
        emoji: "✅",
      },
      {
        id: 10,
        features: { income: 18000, creditScore: 580, age: 23, employed: false },
        label: "rejected",
        emoji: "❌",
      },
      {
        id: 11,
        features: { income: 70000, creditScore: 750, age: 40, employed: true },
        label: "approved",
        emoji: "✅",
      },
      {
        id: 12,
        features: { income: 22000, creditScore: 590, age: 24, employed: false },
        label: "rejected",
        emoji: "❌",
      },
    ],
    availableQuestions: [
      {
        id: "q1",
        feature: "creditScore",
        displayText: "Credit Score ≥ 650?",
        type: "numerical",
        threshold: 650,
      },
      {
        id: "q2",
        feature: "income",
        displayText: "Annual Income ≥ $40,000?",
        type: "numerical",
        threshold: 40000,
      },
      {
        id: "q3",
        feature: "employed",
        displayText: "Currently Employed?",
        type: "categorical",
        categories: ["true"],
      },
      {
        id: "q4",
        feature: "age",
        displayText: "Age ≥ 25 years?",
        type: "numerical",
        threshold: 25,
      },
      {
        id: "q5",
        feature: "creditScore",
        displayText: "Credit Score ≥ 700?",
        type: "numerical",
        threshold: 700,
      },
    ],
  },
  {
    id: "customer-churn",
    title: "Customer Churn Prediction",
    description: "Predict if customers will leave or stay with the service",
    emoji: "📊",
    targetDepth: 4,
    minAccuracy: 80,
    dataset: [
      {
        id: 1,
        features: { monthlyCharge: 80, contractLength: 24, supportCalls: 0, satisfaction: "high" },
        label: "stay",
        emoji: "💚",
      },
      {
        id: 2,
        features: { monthlyCharge: 120, contractLength: 1, supportCalls: 5, satisfaction: "low" },
        label: "churn",
        emoji: "💔",
      },
      {
        id: 3,
        features: {
          monthlyCharge: 60,
          contractLength: 12,
          supportCalls: 1,
          satisfaction: "medium",
        },
        label: "stay",
        emoji: "💚",
      },
      {
        id: 4,
        features: { monthlyCharge: 150, contractLength: 1, supportCalls: 8, satisfaction: "low" },
        label: "churn",
        emoji: "💔",
      },
      {
        id: 5,
        features: { monthlyCharge: 70, contractLength: 24, supportCalls: 0, satisfaction: "high" },
        label: "stay",
        emoji: "💚",
      },
      {
        id: 6,
        features: {
          monthlyCharge: 100,
          contractLength: 6,
          supportCalls: 3,
          satisfaction: "medium",
        },
        label: "stay",
        emoji: "💚",
      },
      {
        id: 7,
        features: { monthlyCharge: 130, contractLength: 1, supportCalls: 6, satisfaction: "low" },
        label: "churn",
        emoji: "💔",
      },
      {
        id: 8,
        features: { monthlyCharge: 55, contractLength: 12, supportCalls: 1, satisfaction: "high" },
        label: "stay",
        emoji: "💚",
      },
      {
        id: 9,
        features: { monthlyCharge: 90, contractLength: 24, supportCalls: 2, satisfaction: "high" },
        label: "stay",
        emoji: "💚",
      },
      {
        id: 10,
        features: { monthlyCharge: 140, contractLength: 1, supportCalls: 7, satisfaction: "low" },
        label: "churn",
        emoji: "💔",
      },
      {
        id: 11,
        features: {
          monthlyCharge: 75,
          contractLength: 12,
          supportCalls: 1,
          satisfaction: "medium",
        },
        label: "stay",
        emoji: "💚",
      },
      {
        id: 12,
        features: { monthlyCharge: 110, contractLength: 6, supportCalls: 4, satisfaction: "low" },
        label: "churn",
        emoji: "💔",
      },
      {
        id: 13,
        features: { monthlyCharge: 65, contractLength: 24, supportCalls: 0, satisfaction: "high" },
        label: "stay",
        emoji: "💚",
      },
      {
        id: 14,
        features: { monthlyCharge: 125, contractLength: 1, supportCalls: 9, satisfaction: "low" },
        label: "churn",
        emoji: "💔",
      },
      {
        id: 15,
        features: { monthlyCharge: 85, contractLength: 12, supportCalls: 2, satisfaction: "high" },
        label: "stay",
        emoji: "💚",
      },
    ],
    availableQuestions: [
      {
        id: "q1",
        feature: "contractLength",
        displayText: "Contract ≥ 12 months?",
        type: "numerical",
        threshold: 12,
      },
      {
        id: "q2",
        feature: "supportCalls",
        displayText: "Support Calls ≥ 4?",
        type: "numerical",
        threshold: 4,
      },
      {
        id: "q3",
        feature: "satisfaction",
        displayText: "Satisfaction: High or Medium?",
        type: "categorical",
        categories: ["high", "medium"],
      },
      {
        id: "q4",
        feature: "monthlyCharge",
        displayText: "Monthly Charge ≥ $100?",
        type: "numerical",
        threshold: 100,
      },
      {
        id: "q5",
        feature: "supportCalls",
        displayText: "Support Calls ≥ 2?",
        type: "numerical",
        threshold: 2,
      },
      {
        id: "q6",
        feature: "satisfaction",
        displayText: "Satisfaction: Low?",
        type: "categorical",
        categories: ["low"],
      },
    ],
  },
  {
    id: "fruit-classifier",
    title: "Fruit Classification",
    description: "Classify fruits based on their properties",
    emoji: "🍎",
    targetDepth: 3,
    minAccuracy: 90,
    dataset: [
      {
        id: 1,
        features: { color: "red", size: "medium", taste: "sweet", seeds: "few" },
        label: "apple",
        emoji: "🍎",
      },
      {
        id: 2,
        features: { color: "yellow", size: "medium", taste: "sweet", seeds: "none" },
        label: "banana",
        emoji: "🍌",
      },
      {
        id: 3,
        features: { color: "orange", size: "medium", taste: "citrus", seeds: "few" },
        label: "orange",
        emoji: "🍊",
      },
      {
        id: 4,
        features: { color: "red", size: "small", taste: "sweet", seeds: "many" },
        label: "strawberry",
        emoji: "🍓",
      },
      {
        id: 5,
        features: { color: "green", size: "small", taste: "sweet", seeds: "many" },
        label: "grape",
        emoji: "🍇",
      },
      {
        id: 6,
        features: { color: "red", size: "medium", taste: "sweet", seeds: "few" },
        label: "apple",
        emoji: "🍎",
      },
      {
        id: 7,
        features: { color: "yellow", size: "medium", taste: "sweet", seeds: "none" },
        label: "banana",
        emoji: "🍌",
      },
      {
        id: 8,
        features: { color: "orange", size: "medium", taste: "citrus", seeds: "few" },
        label: "orange",
        emoji: "🍊",
      },
      {
        id: 9,
        features: { color: "green", size: "medium", taste: "sweet", seeds: "few" },
        label: "apple",
        emoji: "🍏",
      },
      {
        id: 10,
        features: { color: "red", size: "small", taste: "sweet", seeds: "many" },
        label: "strawberry",
        emoji: "🍓",
      },
    ],
    availableQuestions: [
      {
        id: "q1",
        feature: "color",
        displayText: "Color: Yellow?",
        type: "categorical",
        categories: ["yellow"],
      },
      {
        id: "q2",
        feature: "size",
        displayText: "Size: Small?",
        type: "categorical",
        categories: ["small"],
      },
      {
        id: "q3",
        feature: "taste",
        displayText: "Taste: Citrus?",
        type: "categorical",
        categories: ["citrus"],
      },
      {
        id: "q4",
        feature: "seeds",
        displayText: "Seeds: Many?",
        type: "categorical",
        categories: ["many"],
      },
      {
        id: "q5",
        feature: "color",
        displayText: "Color: Red or Green?",
        type: "categorical",
        categories: ["red", "green"],
      },
    ],
  },
];
