import type {
  CaptchaBlueprint,
  CaptchaChallengeDefinition,
  CaptchaChallengeMetadata,
  CaptchaVisualPreset,
} from "./types";

const VISUAL_PRESETS: Record<string, CaptchaVisualPreset> = {
  auroraGlass: {
    id: "aurora-glass",
    name: "Aurora Glass",
    gradient: {
      start: "rgba(18, 34, 68, 0.92)",
      end: "rgba(10, 20, 44, 0.86)",
      accent: "rgba(110, 245, 255, 0.22)",
      angle: 135,
    },
    accentColor: "#6EF5FF",
    saturation: 1.1,
    brightness: 0.96,
    hueShift: -4,
    vignetteStrength: 0.58,
    glowIntensity: 0.68,
    grainOpacity: 0.08,
    gridOpacity: 0.32,
    weight: 0.35,
  },
  ionForge: {
    id: "ion-forge",
    name: "Ion Forge",
    gradient: {
      start: "rgba(24, 20, 42, 0.94)",
      end: "rgba(12, 16, 28, 0.88)",
      accent: "rgba(255, 165, 100, 0.18)",
      angle: 120,
    },
    accentColor: "#FFB966",
    saturation: 1.08,
    brightness: 0.98,
    hueShift: 12,
    vignetteStrength: 0.52,
    glowIntensity: 0.62,
    grainOpacity: 0.06,
    gridOpacity: 0.28,
    weight: 0.25,
  },
  violetNebula: {
    id: "violet-nebula",
    name: "Violet Nebula",
    gradient: {
      start: "rgba(32, 18, 58, 0.9)",
      end: "rgba(16, 8, 32, 0.88)",
      accent: "rgba(184, 120, 255, 0.22)",
      angle: 150,
    },
    accentColor: "#B67CFF",
    saturation: 1.18,
    brightness: 0.94,
    hueShift: 22,
    vignetteStrength: 0.64,
    glowIntensity: 0.72,
    grainOpacity: 0.1,
    gridOpacity: 0.34,
    weight: 0.2,
  },
  deepCyan: {
    id: "deep-cyan",
    name: "Deep Cyan",
    gradient: {
      start: "rgba(10, 28, 36, 0.9)",
      end: "rgba(8, 18, 26, 0.94)",
      accent: "rgba(96, 220, 224, 0.2)",
      angle: 110,
    },
    accentColor: "#60DDE0",
    saturation: 1.04,
    brightness: 1.0,
    hueShift: -10,
    vignetteStrength: 0.48,
    glowIntensity: 0.56,
    grainOpacity: 0.05,
    gridOpacity: 0.26,
    weight: 0.2,
  },
} as const;

const pickVisualPresets = (...keys: (keyof typeof VISUAL_PRESETS)[]) => keys.map((key) => ({ ...VISUAL_PRESETS[key], gradient: { ...VISUAL_PRESETS[key].gradient } }));

const BLUEPRINTS: CaptchaBlueprint[] = [
  {
    id: "find-rockets",
    title: "Rocket Detection",
    prompt: "Find all rockets",
    gridSize: 3,
    difficulty: "standard",
    layouts: [
      { mode: "uniform", weight: 0.5 },
      { mode: "cluster", weight: 0.3, clusterCount: [1, 2], clusterSize: [2, 3] },
      { mode: "sweep", weight: 0.2 },
    ],
    visualStyles: pickVisualPresets("auroraGlass", "violetNebula", "deepCyan"),
    target: {
      label: "rocket",
      spriteSet: "rocket",
      min: 2,
      max: 3,
    },
    distractors: [
      { label: "repair-capsule", spriteSet: "repair-capsule", weight: 0.4 },
      { label: "beacon-drone", spriteSet: "beacon-drone", weight: 0.3 },
      { label: "alien-grey", spriteSet: "alien-grey", weight: 0.3 },
    ],
    distractorCount: {
      min: 3,
      max: 5,
    },
    backgrounds: ["nebula", "orbital", "minimal"],
  },
  {
    id: "find-crystals",
    title: "Crystal Hunt",
    prompt: "Collect energy crystals",
    gridSize: 4,
    difficulty: "hard",
    layouts: [
      { mode: "uniform", weight: 0.4 },
      { mode: "cluster", weight: 0.4, clusterCount: [1, 2], clusterSize: [3, 4] },
      { mode: "orbit", weight: 0.2 },
    ],
    visualStyles: pickVisualPresets("deepCyan", "auroraGlass", "violetNebula"),
    target: {
      label: "crystal",
      spriteSet: "crystal",
      min: 3,
      max: 5,
    },
    distractors: [
      { label: "beacon-drone", spriteSet: "beacon-drone", weight: 0.3 },
      { label: "space-gun", spriteSet: "space-gun", weight: 0.35 },
      { label: "solar-relay", spriteSet: "solar-relay", weight: 0.35 },
    ],
    distractorCount: {
      min: 4,
      max: 7,
    },
    backgrounds: ["nebula", "orbital"],
  },
  {
    id: "find-alien-cats",
    title: "Alien Cat Chase",
    prompt: "Catch the alien cats",
    gridSize: 3,
    difficulty: "casual",
    layouts: [
      { mode: "uniform", weight: 0.5 },
      { mode: "sweep", weight: 0.3 },
      { mode: "cluster", weight: 0.2, clusterCount: [1, 2], clusterSize: [2, 3] },
    ],
    visualStyles: pickVisualPresets("ionForge", "deepCyan", "auroraGlass"),
    target: {
      label: "alien-cat",
      spriteSet: "alien-cat",
      min: 2,
      max: 3,
    },
    distractors: [
      { label: "alien-grey", spriteSet: "alien-grey", weight: 0.4 },
      { label: "rocket", spriteSet: "rocket", weight: 0.3 },
      { label: "repair-capsule", spriteSet: "repair-capsule", weight: 0.3 },
    ],
    distractorCount: {
      min: 2,
      max: 4,
    },
    backgrounds: ["nebula", "orbital"],
  },
  {
    id: "find-space-guns",
    title: "Weapon Cache",
    prompt: "Locate space guns",
    gridSize: 4,
    difficulty: "standard",
    layouts: [
      { mode: "uniform", weight: 0.4 },
      { mode: "cluster", weight: 0.4, clusterCount: [1, 2], clusterSize: [2, 4] },
      { mode: "orbit", weight: 0.2 },
    ],
    visualStyles: pickVisualPresets("ionForge", "violetNebula", "deepCyan"),
    target: {
      label: "space-gun",
      spriteSet: "space-gun",
      min: 3,
      max: 4,
    },
    distractors: [
      { label: "laser-sword", spriteSet: "laser-sword", weight: 0.4 },
      { label: "beacon-drone", spriteSet: "beacon-drone", weight: 0.3 },
      { label: "crystal", spriteSet: "crystal", weight: 0.3 },
    ],
    distractorCount: {
      min: 4,
      max: 6,
    },
    backgrounds: ["orbital", "minimal"],
  },
  {
    id: "find-grey-aliens",
    title: "Alien Contact",
    prompt: "Identify grey aliens",
    gridSize: 5,
    difficulty: "hard",
    layouts: [
      { mode: "uniform", weight: 0.3 },
      { mode: "cluster", weight: 0.4, clusterCount: [2, 3], clusterSize: [3, 5] },
      { mode: "orbit", weight: 0.3 },
    ],
    visualStyles: pickVisualPresets("auroraGlass", "violetNebula", "ionForge"),
    target: {
      label: "alien-grey",
      spriteSet: "alien-grey",
      min: 4,
      max: 6,
    },
    distractors: [
      { label: "alien-cat", spriteSet: "alien-cat", weight: 0.3 },
      { label: "repair-capsule", spriteSet: "repair-capsule", weight: 0.35 },
      { label: "solar-relay", spriteSet: "solar-relay", weight: 0.35 },
    ],
    distractorCount: {
      min: 6,
      max: 10,
    },
    backgrounds: ["nebula", "orbital"],
  },
  {
    id: "find-repair-capsules",
    title: "Repair Capsules",
    prompt: "Find all repair capsules",
    gridSize: 3,
    difficulty: "casual",
    layouts: [
      { mode: "uniform", weight: 0.4 },
      { mode: "cluster", weight: 0.35, clusterCount: [1, 2], clusterSize: [2, 4] },
      { mode: "sweep", weight: 0.25 },
    ],
    visualStyles: pickVisualPresets("auroraGlass", "deepCyan"),
    target: {
      label: "repair-capsule",
      spriteSet: "repair-capsule",
      min: 2,
      max: 3,
    },
    distractors: [
      { label: "beacon-drone", spriteSet: "beacon-drone", weight: 0.35 },
      { label: "solar-relay", spriteSet: "solar-relay", weight: 0.35 },
      { label: "alien-grey", spriteSet: "alien-grey", weight: 0.3 },
    ],
    distractorCount: {
      min: 2,
      max: 4,
    },
    backgrounds: ["nebula", "orbital"],
  },
  {
    id: "find-laser-swords",
    title: "Laser Swords",
    prompt: "Find all laser swords",
    gridSize: 4,
    difficulty: "standard",
    layouts: [
      { mode: "uniform", weight: 0.3 },
      { mode: "cluster", weight: 0.4, clusterCount: [1, 2], clusterSize: [3, 5] },
      { mode: "orbit", weight: 0.3 },
    ],
    visualStyles: pickVisualPresets("ionForge", "violetNebula"),
    target: {
      label: "laser-sword",
      spriteSet: "laser-sword",
      min: 3,
      max: 5,
    },
    distractors: [
      { label: "space-gun", spriteSet: "space-gun", weight: 0.4 },
      { label: "rocket", spriteSet: "rocket", weight: 0.3 },
      { label: "alien-cat", spriteSet: "alien-cat", weight: 0.3 },
    ],
    distractorCount: {
      min: 3,
      max: 5,
    },
    backgrounds: ["orbital", "minimal"],
  },
  {
    id: "find-beacon-drones",
    title: "Beacon Drones",
    prompt: "Locate all beacon drones",
    gridSize: 3,
    difficulty: "casual",
    layouts: [
      { mode: "uniform", weight: 0.35 },
      { mode: "swarm", weight: 0.35 },
      { mode: "sweep", weight: 0.3 },
    ],
    visualStyles: pickVisualPresets("auroraGlass", "deepCyan", "ionForge"),
    target: {
      label: "beacon-drone",
      spriteSet: "beacon-drone",
      min: 2,
      max: 4,
    },
    distractors: [
      { label: "solar-relay", spriteSet: "solar-relay", weight: 0.4 },
      { label: "repair-capsule", spriteSet: "repair-capsule", weight: 0.35 },
      { label: "crystal", spriteSet: "crystal", weight: 0.25 },
    ],
    distractorCount: {
      min: 2,
      max: 4,
    },
    backgrounds: ["nebula", "orbital"],
  },
  {
    id: "find-solar-relays",
    title: "Solar Relays",
    prompt: "Mark all solar relays",
    gridSize: 4,
    difficulty: "standard",
    layouts: [
      { mode: "uniform", weight: 0.3 },
      { mode: "cluster", weight: 0.4, clusterCount: [2, 3], clusterSize: [3, 5] },
      { mode: "sweep", weight: 0.3 },
    ],
    visualStyles: pickVisualPresets("violetNebula", "deepCyan"),
    target: {
      label: "solar-relay",
      spriteSet: "solar-relay",
      min: 3,
      max: 5,
    },
    distractors: [
      { label: "beacon-drone", spriteSet: "beacon-drone", weight: 0.4 },
      { label: "alien-grey", spriteSet: "alien-grey", weight: 0.35 },
      { label: "alien-cat", spriteSet: "alien-cat", weight: 0.25 },
    ],
    distractorCount: {
      min: 4,
      max: 6,
    },
    backgrounds: ["orbital", "minimal"],
  },
  {
    id: "find-rockets-hard",
    title: "Rocket Fleet",
    prompt: "Target all rockets",
    gridSize: 5,
    difficulty: "hard",
    layouts: [
      { mode: "uniform", weight: 0.25 },
      { mode: "swarm", weight: 0.3 },
      { mode: "cluster", weight: 0.25, clusterCount: [2, 3], clusterSize: [4, 6] },
      { mode: "orbit", weight: 0.2 },
    ],
    visualStyles: pickVisualPresets("auroraGlass", "violetNebula", "ionForge"),
    target: {
      label: "rocket",
      spriteSet: "rocket",
      min: 4,
      max: 6,
    },
    distractors: [
      { label: "repair-capsule", spriteSet: "repair-capsule", weight: 0.35 },
      { label: "space-gun", spriteSet: "space-gun", weight: 0.35 },
      { label: "laser-sword", spriteSet: "laser-sword", weight: 0.3 },
    ],
    distractorCount: {
      min: 5,
      max: 8,
    },
    backgrounds: ["nebula", "orbital"],
  },
  {
    id: "find-crystals-easy",
    title: "Crystal Hunt",
    prompt: "Collect all crystals",
    gridSize: 3,
    difficulty: "casual",
    layouts: [
      { mode: "uniform", weight: 0.4 },
      { mode: "cluster", weight: 0.35, clusterCount: [1, 2], clusterSize: [2, 4] },
      { mode: "sweep", weight: 0.25 },
    ],
    visualStyles: pickVisualPresets("ionForge", "deepCyan"),
    target: {
      label: "crystal",
      spriteSet: "crystal",
      min: 2,
      max: 3,
    },
    distractors: [
      { label: "solar-relay", spriteSet: "solar-relay", weight: 0.35 },
      { label: "beacon-drone", spriteSet: "beacon-drone", weight: 0.35 },
      { label: "repair-capsule", spriteSet: "repair-capsule", weight: 0.3 },
    ],
    distractorCount: {
      min: 2,
      max: 4,
    },
    backgrounds: ["orbital", "minimal"],
  },
  {
    id: "find-space-guns-med",
    title: "Weapon Cache",
    prompt: "Secure all space guns",
    gridSize: 4,
    difficulty: "standard",
    layouts: [
      { mode: "uniform", weight: 0.3 },
      { mode: "swarm", weight: 0.3 },
      { mode: "cluster", weight: 0.25, clusterCount: [1, 2], clusterSize: [3, 5] },
      { mode: "orbit", weight: 0.15 },
    ],
    visualStyles: pickVisualPresets("violetNebula", "auroraGlass", "ionForge"),
    target: {
      label: "space-gun",
      spriteSet: "space-gun",
      min: 3,
      max: 5,
    },
    distractors: [
      { label: "laser-sword", spriteSet: "laser-sword", weight: 0.4 },
      { label: "rocket", spriteSet: "rocket", weight: 0.35 },
      { label: "alien-grey", spriteSet: "alien-grey", weight: 0.25 },
    ],
    distractorCount: {
      min: 3,
      max: 5,
    },
    backgrounds: ["nebula", "orbital"],
  },
  {
    id: "find-alien-cats-med",
    title: "Alien Cats",
    prompt: "Find all alien cats",
    gridSize: 4,
    difficulty: "standard",
    layouts: [
      { mode: "uniform", weight: 0.35 },
      { mode: "cluster", weight: 0.35, clusterCount: [1, 2], clusterSize: [3, 5] },
      { mode: "sweep", weight: 0.3 },
    ],
    visualStyles: pickVisualPresets("deepCyan", "ionForge", "violetNebula"),
    target: {
      label: "alien-cat",
      spriteSet: "alien-cat",
      min: 3,
      max: 4,
    },
    distractors: [
      { label: "alien-grey", spriteSet: "alien-grey", weight: 0.4 },
      { label: "crystal", spriteSet: "crystal", weight: 0.35 },
      { label: "beacon-drone", spriteSet: "beacon-drone", weight: 0.25 },
    ],
    distractorCount: {
      min: 3,
      max: 5,
    },
    backgrounds: ["orbital", "minimal"],
  },
  {
    id: "find-alien-greys-easy",
    title: "Grey Aliens",
    prompt: "Spot all grey aliens",
    gridSize: 3,
    difficulty: "casual",
    layouts: [
      { mode: "uniform", weight: 0.4 },
      { mode: "cluster", weight: 0.35, clusterCount: [1, 2], clusterSize: [2, 4] },
      { mode: "swarm", weight: 0.25 },
    ],
    visualStyles: pickVisualPresets("auroraGlass", "violetNebula"),
    target: {
      label: "alien-grey",
      spriteSet: "alien-grey",
      min: 2,
      max: 3,
    },
    distractors: [
      { label: "alien-cat", spriteSet: "alien-cat", weight: 0.4 },
      { label: "solar-relay", spriteSet: "solar-relay", weight: 0.35 },
      { label: "repair-capsule", spriteSet: "repair-capsule", weight: 0.25 },
    ],
    distractorCount: {
      min: 2,
      max: 4,
    },
    backgrounds: ["nebula", "orbital"],
  },
  {
    id: "find-crystals-hard",
    title: "Crystal Field",
    prompt: "Harvest all crystals",
    gridSize: 5,
    difficulty: "hard",
    layouts: [
      { mode: "uniform", weight: 0.25 },
      { mode: "sweep", weight: 0.3 },
      { mode: "cluster", weight: 0.25, clusterCount: [2, 3], clusterSize: [4, 6] },
      { mode: "orbit", weight: 0.2 },
    ],
    visualStyles: pickVisualPresets("deepCyan", "auroraGlass", "ionForge"),
    target: {
      label: "crystal",
      spriteSet: "crystal",
      min: 4,
      max: 6,
    },
    distractors: [
      { label: "beacon-drone", spriteSet: "beacon-drone", weight: 0.35 },
      { label: "alien-cat", spriteSet: "alien-cat", weight: 0.35 },
      { label: "space-gun", spriteSet: "space-gun", weight: 0.3 },
    ],
    distractorCount: {
      min: 5,
      max: 8,
    },
    backgrounds: ["orbital", "minimal"],
  },
  {
    id: "find-laser-swords-med",
    title: "Laser Sword Collection",
    prompt: "Collect all laser swords",
    gridSize: 4,
    difficulty: "standard",
    layouts: [
      { mode: "uniform", weight: 0.3 },
      { mode: "swarm", weight: 0.35 },
      { mode: "cluster", weight: 0.25, clusterCount: [1, 2], clusterSize: [3, 5] },
      { mode: "orbit", weight: 0.1 },
    ],
    visualStyles: pickVisualPresets("ionForge", "violetNebula", "auroraGlass"),
    target: {
      label: "laser-sword",
      spriteSet: "laser-sword",
      min: 3,
      max: 5,
    },
    distractors: [
      { label: "space-gun", spriteSet: "space-gun", weight: 0.4 },
      { label: "beacon-drone", spriteSet: "beacon-drone", weight: 0.35 },
      { label: "alien-grey", spriteSet: "alien-grey", weight: 0.25 },
    ],
    distractorCount: {
      min: 4,
      max: 6,
    },
    backgrounds: ["nebula", "orbital"],
  },
  {
    id: "find-repair-capsules-hard",
    title: "Repair Emergency",
    prompt: "Locate all repair capsules",
    gridSize: 5,
    difficulty: "hard",
    layouts: [
      { mode: "uniform", weight: 0.3 },
      { mode: "cluster", weight: 0.35, clusterCount: [2, 3], clusterSize: [4, 7] },
      { mode: "sweep", weight: 0.2 },
      { mode: "orbit", weight: 0.15 },
    ],
    visualStyles: pickVisualPresets("violetNebula", "deepCyan", "ionForge"),
    target: {
      label: "repair-capsule",
      spriteSet: "repair-capsule",
      min: 4,
      max: 6,
    },
    distractors: [
      { label: "rocket", spriteSet: "rocket", weight: 0.35 },
      { label: "solar-relay", spriteSet: "solar-relay", weight: 0.35 },
      { label: "laser-sword", spriteSet: "laser-sword", weight: 0.3 },
    ],
    distractorCount: {
      min: 5,
      max: 8,
    },
    backgrounds: ["orbital", "minimal"],
  },
];

export const CAPTCHA_BLUEPRINTS = BLUEPRINTS;

export const createChallengePlaceholders = (count: number): CaptchaChallengeDefinition[] => {
  return Array.from({ length: count }, (_, index) => {
    const blueprint = BLUEPRINTS[index % BLUEPRINTS.length];
    const metadata: CaptchaChallengeMetadata = {
      blueprintId: blueprint.id,
      targetLabel: blueprint.target.label,
      difficulty: blueprint.difficulty,
      seed: null,
      backgroundId: null,
      blueprint,
    };

    return {
      id: `${blueprint.id}-${index}`,
      title: blueprint.title,
      prompt: blueprint.prompt,
      backgroundImage: "",
      alt: `${blueprint.title} background`,
      gridSize: blueprint.gridSize,
      correctCells: [],
      tileSprites: {},
      metadata,
    };
  });
};
