import type { CaptchaChallengeDefinition, CaptchaChallengeMetadata } from "./types";

// Доступные большие картинки из public/mock/mini-games/captcha/ с правильными ответами
const FULL_IMAGES = [
  {
    id: "rocket",
    src: "/mock/mini-games/captcha/rocket.webp",
    label: "rocket",
    prompt: "Highlight every tile that contains an active rocket",
    title: "Launch Pad Sweep",
    gridSize: 3,
    correctCells: [1, 2, 4, 5],
  },
  {
    id: "astronaut",
    src: "/mock/mini-games/captcha/astronaut.webp",
    label: "astronaut",
    prompt: "Mark the panels showing astronauts on EVA duty",
    title: "Orbit Crew Check",
    gridSize: 3,
    correctCells: [1, 3, 4, 5, 7],
  },
  {
    id: "ufo",
    src: "/mock/mini-games/captcha/UFO.webp",
    label: "UFO",
    prompt: "Select the luminous objects that do not belong to the fleet",
    title: "Identify the Intruders",
    gridSize: 3,
    correctCells: [1, 3, 4, 5, 6, 7, 8],
  },
  {
    id: "aliens",
    src: "/mock/mini-games/captcha/aliens.webp",
    label: "aliens",
    prompt: "Tap the tiles where you spot extraterrestrial silhouettes",
    title: "Alien Signals",
    gridSize: 4,
    correctCells: [5, 8, 9, 10, 11, 12, 13, 14],
  },
  {
    id: "crystal",
    src: "/mock/mini-games/captcha/kristal.webp",
    label: "crystal",
    prompt: "Locate the tiles containing the glowing crystal shards",
    title: "Crystal Cache",
    gridSize: 4,
    correctCells: [4, 5, 8, 11, 12, 14, 15],
  },
  {
    id: "energy",
    src: "/mock/mini-games/captcha/ligthball.webp",
    label: "energy orb",
    prompt: "Trace the drifting energy spheres across the grid",
    title: "Energy Orbs",
    gridSize: 5,
    correctCells: [7, 10, 11, 12, 16, 17],
  },
  {
    id: "mushrooms",
    src: "/mock/mini-games/captcha/mashrooms.webp",
    label: "mushrooms",
    prompt: "Spot the luminescent fungi thriving on the alien terrain",
    title: "Biolum Mushrooms",
    gridSize: 4,
    correctCells: [12],
  },
  {
    id: "planets",
    src: "/mock/mini-games/captcha/planets.webp",
    label: "planets",
    prompt: "Select the tiles showing planets",
    title: "Solar Panels",
    gridSize: 5,
    correctCells: [1, 3, 4, 5],
  },
  {
    id: "rovers",
    src: "/mock/mini-games/captcha/rovers.webp",
    label: "rover",
    prompt: "Identify the panels showing active reconnaissance rovers",
    title: "Rover Fleet",
    gridSize: 5,
    correctCells: [6, 7, 11, 12, 13, 14, 16, 17],
  },
  // === НОВЫЕ ИЗОБРАЖЕНИЯ ===
  {
    id: "space-station-01",
    src: "/mock/mini-games/captcha/space-station-01.webp",
    label: "space station",
    prompt: "Select tiles showing parts of the orbital station",
    title: "Station Assembly",
    gridSize: 4,
    correctCells: [2, 3, 5, 6, 7, 9, 10, 11],
  },
  {
    id: "space-station-02",
    src: "/mock/mini-games/captcha/space-station-02.webp",
    label: "docking port",
    prompt: "Mark the tiles with visible docking mechanisms",
    title: "Docking Protocol",
    gridSize: 3,
    correctCells: [1, 4, 5, 7],
  },
  {
    id: "space-station-03",
    src: "/mock/mini-games/captcha/space-station-03.webp",
    label: "solar panel",
    prompt: "Highlight the station's energy collection arrays",
    title: "Power Grid Check",
    gridSize: 5,
    correctCells: [3, 4, 8, 9, 13, 14, 18, 19],
  },
  {
    id: "nebula-01",
    src: "/mock/mini-games/captcha/nebula-01.webp",
    label: "nebula cloud",
    prompt: "Select areas with dense cosmic gas formations",
    title: "Nebula Survey",
    gridSize: 3,
    correctCells: [0, 1, 2, 3, 4, 5],
  },
  {
    id: "nebula-02",
    src: "/mock/mini-games/captcha/nebula-02.webp",
    label: "star formation",
    prompt: "Mark regions where new stars are being born",
    title: "Stellar Genesis",
    gridSize: 4,
    correctCells: [1, 2, 5, 6, 9, 10],
  },
  {
    id: "nebula-03",
    src: "/mock/mini-games/captcha/nebula-03.webp",
    label: "emission nebula",
    prompt: "Identify the glowing hydrogen clouds",
    title: "Emission Mapping",
    gridSize: 4,
    correctCells: [4, 5, 6, 7, 8, 9, 10, 11, 12],
  },
  {
    id: "nebula-04",
    src: "/mock/mini-games/captcha/nebula-04.webp",
    label: "dark matter",
    prompt: "Spot the darker regions blocking starlight",
    title: "Shadow Nebula",
    gridSize: 3,
    correctCells: [0, 3, 6],
  },
  {
    id: "galaxy-01",
    src: "/mock/mini-games/captcha/galaxy-01.webp",
    label: "spiral arms",
    prompt: "Trace the galaxy's rotating spiral structures",
    title: "Spiral Tracer",
    gridSize: 5,
    correctCells: [2, 7, 12, 17, 22],
  },
  {
    id: "galaxy-02",
    src: "/mock/mini-games/captcha/galaxy-02.webp",
    label: "galactic core",
    prompt: "Locate the bright central region of the galaxy",
    title: "Core Detection",
    gridSize: 4,
    correctCells: [5, 6, 9, 10],
  },
  {
    id: "galaxy-03",
    src: "/mock/mini-games/captcha/galaxy-03.webp",
    label: "star clusters",
    prompt: "Mark the densely packed stellar groups",
    title: "Cluster Survey",
    gridSize: 5,
    correctCells: [1, 6, 11, 16, 21],
  },
  {
    id: "cosmic-dust-01",
    src: "/mock/mini-games/captcha/cosmic-dust-01.webp",
    label: "dust lanes",
    prompt: "Identify the interstellar dust obscuring the view",
    title: "Dust Mapping",
    gridSize: 3,
    correctCells: [2, 4, 5, 7, 8],
  },
  {
    id: "asteroid-field-01",
    src: "/mock/mini-games/captcha/asteroid-field-01.webp",
    label: "asteroids",
    prompt: "Select tiles containing space rocks and debris",
    title: "Asteroid Belt",
    gridSize: 4,
    correctCells: [0, 1, 2, 4, 5, 8, 9, 12],
  },
  {
    id: "planet-surface-01",
    src: "/mock/mini-games/captcha/planet-surface-01.webp",
    label: "crater",
    prompt: "Mark the impact craters on the surface",
    title: "Crater Analysis",
    gridSize: 3,
    correctCells: [1, 3, 5, 7],
  },
  {
    id: "planet-surface-02",
    src: "/mock/mini-games/captcha/planet-surface-02.webp",
    label: "mountain range",
    prompt: "Highlight the elevated terrain features",
    title: "Topography Scan",
    gridSize: 4,
    correctCells: [2, 3, 6, 7, 10, 11],
  },
  {
    id: "planet-surface-03",
    src: "/mock/mini-games/captcha/planet-surface-03.webp",
    label: "volcanic region",
    prompt: "Identify areas with volcanic activity",
    title: "Volcanic Survey",
    gridSize: 5,
    correctCells: [7, 12, 17],
  },
  {
    id: "alien-landscape-01",
    src: "/mock/mini-games/captcha/alien-landscape-01.webp",
    label: "alien flora",
    prompt: "Spot the extraterrestrial plant life",
    title: "Xenobotany",
    gridSize: 4,
    correctCells: [8, 9, 12, 13],
  },
  {
    id: "alien-landscape-02",
    src: "/mock/mini-games/captcha/alien-landscape-02.webp",
    label: "alien structures",
    prompt: "Locate the non-natural constructions",
    title: "Artifact Hunt",
    gridSize: 3,
    correctCells: [2, 5, 8],
  },
  {
    id: "deep-space-01",
    src: "/mock/mini-games/captcha/deep-space-01.webp",
    label: "distant galaxies",
    prompt: "Mark the faint galaxy clusters in deep space",
    title: "Deep Field",
    gridSize: 5,
    correctCells: [0, 4, 12, 20, 24],
  },
  {
    id: "deep-space-02",
    src: "/mock/mini-games/captcha/deep-space-02.webp",
    label: "cosmic void",
    prompt: "Identify the empty regions between structures",
    title: "Void Mapper",
    gridSize: 3,
    correctCells: [1, 4, 7],
  },
  {
    id: "starfield-01",
    src: "/mock/mini-games/captcha/starfield-01.webp",
    label: "bright stars",
    prompt: "Select the most luminous stellar objects",
    title: "Star Brightness",
    gridSize: 4,
    correctCells: [1, 3, 5, 7, 9, 11, 13, 15],
  },
  {
    id: "starfield-02",
    src: "/mock/mini-games/captcha/starfield-02.webp",
    label: "binary stars",
    prompt: "Find the paired stellar systems",
    title: "Binary Hunter",
    gridSize: 5,
    correctCells: [6, 7, 11, 12, 16, 17],
  },
  {
    id: "starfield-03",
    src: "/mock/mini-games/captcha/starfield-03.webp",
    label: "constellation",
    prompt: "Trace the pattern connecting these stars",
    title: "Star Pattern",
    gridSize: 3,
    correctCells: [0, 2, 4, 6, 8],
  },
  {
    id: "solar-system-01",
    src: "/mock/mini-games/captcha/solar-system-01.webp",
    label: "inner planets",
    prompt: "Identify the rocky terrestrial worlds",
    title: "Inner System",
    gridSize: 4,
    correctCells: [4, 5, 6, 7],
  },
  {
    id: "solar-system-02",
    src: "/mock/mini-games/captcha/solar-system-02.webp",
    label: "gas giants",
    prompt: "Mark the massive gaseous planets",
    title: "Outer Giants",
    gridSize: 5,
    correctCells: [10, 11, 12, 15, 16, 17],
  },
  {
    id: "black-hole-01",
    src: "/mock/mini-games/captcha/black-hole-01.webp",
    label: "event horizon",
    prompt: "Locate the boundary of the black hole",
    title: "Event Horizon",
    gridSize: 3,
    correctCells: [4],
  },
  {
    id: "black-hole-02",
    src: "/mock/mini-games/captcha/black-hole-02.webp",
    label: "accretion disk",
    prompt: "Highlight the swirling matter around the singularity",
    title: "Accretion Flow",
    gridSize: 4,
    correctCells: [1, 2, 4, 5, 6, 7, 9, 10, 11],
  },
  {
    id: "supernova-01",
    src: "/mock/mini-games/captcha/supernova-01.webp",
    label: "stellar explosion",
    prompt: "Mark the expanding shockwave from the dying star",
    title: "Supernova Remnant",
    gridSize: 5,
    correctCells: [6, 7, 8, 11, 12, 13, 16, 17, 18],
  },
  {
    id: "space-anomaly-01",
    src: "/mock/mini-games/captcha/space-anomaly-01.webp",
    label: "quantum distortion",
    prompt: "Detect the space-time irregularities",
    title: "Anomaly Scan",
    gridSize: 3,
    correctCells: [0, 1, 3, 4],
  },
  {
    id: "space-anomaly-02",
    src: "/mock/mini-games/captcha/space-anomaly-02.webp",
    label: "energy signature",
    prompt: "Trace the unknown energy patterns",
    title: "Signal Analysis",
    gridSize: 4,
    correctCells: [5, 6, 9, 10],
  },
  {
    id: "wormhole-01",
    src: "/mock/mini-games/captcha/wormhole-01.webp",
    label: "wormhole",
    prompt: "Identify the entrance to the spacetime tunnel",
    title: "Wormhole Gateway",
    gridSize: 3,
    correctCells: [1, 4, 7],
  },
  {
    id: "wormhole-02",
    src: "/mock/mini-games/captcha/wormhole-02.webp",
    label: "gravitational lens",
    prompt: "Mark the warped light patterns around the wormhole",
    title: "Gravity Lens",
    gridSize: 5,
    correctCells: [7, 11, 12, 13, 17],
  },
  {
    id: "cosmic-portal-01",
    src: "/mock/mini-games/captcha/cosmic-portal-01.webp",
    label: "dimensional rift",
    prompt: "Locate the tears in the fabric of space",
    title: "Portal Detection",
    gridSize: 4,
    correctCells: [5, 6, 9, 10],
  },
];

// Генерация challenge для режима full-images
// Одна большая картинка делится на сетку, нужно выбрать плитки где виден целевой объект
export function createFullImageChallenge(index: number): CaptchaChallengeDefinition {
  // Выбираем картинку по индексу
  const targetImage = FULL_IMAGES[index % FULL_IMAGES.length];

  // В full-images режиме НЕТ tileSprites - картинка показывается через backgroundImage
  const tileSprites: Record<number, never[]> = {};

  // В full-images режиме НЕ используем renderedImage - картинка загружается через backgroundImage
  const metadata: CaptchaChallengeMetadata = {
    seed: `full-image-${index}`,
    blueprintId: `full-image-${targetImage.id}`,
    targetLabel: targetImage.label,
    difficulty:
      targetImage.gridSize === 3 ? "casual" : targetImage.gridSize === 4 ? "standard" : "hard",
    backgroundId: null,
    blueprint: {
      id: `full-image-${targetImage.id}`,
      title: targetImage.title,
      prompt: targetImage.prompt,
      gridSize: targetImage.gridSize,
      difficulty:
        targetImage.gridSize === 3 ? "casual" : targetImage.gridSize === 4 ? "standard" : "hard",
      target: {
        label: targetImage.label,
        spriteSet: targetImage.id,
        min: targetImage.correctCells.length,
        max: targetImage.correctCells.length,
      },
      distractors: [],
      distractorCount: { min: 0, max: 0 },
      backgrounds: [],
    },
    // renderedImage НЕ используется для full-images режима
  };

  return {
    id: `full-image-challenge-${index}`,
    title: targetImage.title,
    prompt: targetImage.prompt,
    backgroundImage: targetImage.src,
    alt: `Full image challenge: ${targetImage.label}`,
    gridSize: targetImage.gridSize,
    correctCells: [...targetImage.correctCells],
    tileSprites,
    metadata,
  };
}

// Генерация пула челленджей для режима full-images
export function createFullImageChallenges(count: number): CaptchaChallengeDefinition[] {
  return Array.from({ length: count }, (_, index) => createFullImageChallenge(index));
}
